### PR TITLE
Add DateTime support - see https://yaml.org/type/timestamp.html

### PR DESCRIPTION
**Pull request by joerichsen**
This PR adds DateTime support. See see https://yaml.org/type/timestamp.html

### CODE REVIEW

**Comment by mruoss** [comment]
Hi @joerichsen 
Thank you for your PR. Looking at the link you provided made me think that if we support DateTime, we should probably support Date, too, don't you think? Would you want to add that?

Also, please add an entry to `CHANGELOG.md`

In the mean time I'll try to improve the checks. Seems like a caching problem.

**Comment by mruoss** [comment]
Alright, the caching problem should be fixed now. Can you rebase your branch to master, please?

**Comment by joerichsen** [comment]
Sounds good - I will take a look at Date support make this PR ready to be merged :-)

**Comment by mruoss** [comment]
Very nice. Thank you for your contribution!

**Comment by mruoss** [comment]
I get failing tests on Elixir 1.10.x. I must have broken the check for that yesterday. Anyway I will fix that problem before publishing a new version.

**Pull request merged**
